{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2f893983",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting tensorflow\n",
      "  Downloading tensorflow-2.20.0-cp39-cp39-win_amd64.whl.metadata (4.6 kB)\n",
      "Collecting absl-py>=1.0.0 (from tensorflow)\n",
      "  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)\n",
      "Collecting astunparse>=1.6.0 (from tensorflow)\n",
      "  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)\n",
      "Collecting flatbuffers>=24.3.25 (from tensorflow)\n",
      "  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)\n",
      "Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)\n",
      "  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)\n",
      "Collecting google_pasta>=0.1.1 (from tensorflow)\n",
      "  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)\n",
      "Collecting libclang>=13.0.0 (from tensorflow)\n",
      "  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)\n",
      "Requirement already satisfied: opt_einsum>=2.3.2 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (3.4.0)\n",
      "Requirement already satisfied: packaging in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (25.0)\n",
      "Collecting protobuf>=5.28.0 (from tensorflow)\n",
      "  Downloading protobuf-6.33.6-cp39-cp39-win_amd64.whl.metadata (593 bytes)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorflow) (2.28.1)\n",
      "Requirement already satisfied: setuptools in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorflow) (63.4.1)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (1.17.0)\n",
      "Collecting termcolor>=1.1.0 (from tensorflow)\n",
      "  Downloading termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)\n",
      "Requirement already satisfied: typing_extensions>=3.6.6 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (4.12.2)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorflow) (1.14.1)\n",
      "Collecting grpcio<2.0,>=1.24.3 (from tensorflow)\n",
      "  Downloading grpcio-1.80.0-cp39-cp39-win_amd64.whl.metadata (3.9 kB)\n",
      "Collecting tensorboard~=2.20.0 (from tensorflow)\n",
      "  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)\n",
      "Collecting keras>=3.10.0 (from tensorflow)\n",
      "  Downloading keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (1.26.4)\n",
      "Collecting h5py>=3.11.0 (from tensorflow)\n",
      "  Downloading h5py-3.14.0-cp39-cp39-win_amd64.whl.metadata (2.7 kB)\n",
      "Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (0.5.4)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (1.26.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (2022.9.14)\n",
      "Requirement already satisfied: markdown>=2.6.8 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorboard~=2.20.0->tensorflow) (3.3.4)\n",
      "Requirement already satisfied: pillow in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)\n",
      "Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.20.0->tensorflow)\n",
      "  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorboard~=2.20.0->tensorflow) (2.0.3)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from astunparse>=1.6.0->tensorflow) (0.37.1)\n",
      "Collecting rich (from keras>=3.10.0->tensorflow)\n",
      "  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)\n",
      "Collecting namex (from keras>=3.10.0->tensorflow)\n",
      "  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)\n",
      "Collecting optree (from keras>=3.10.0->tensorflow)\n",
      "  Downloading optree-0.19.0-cp39-cp39-win_amd64.whl.metadata (35 kB)\n",
      "Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.10.0->tensorflow)\n",
      "  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)\n",
      "Collecting pygments<3.0.0,>=2.13.0 (from rich->keras>=3.10.0->tensorflow)\n",
      "  Downloading pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)\n",
      "Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow)\n",
      "  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)\n",
      "Downloading tensorflow-2.20.0-cp39-cp39-win_amd64.whl (331.7 MB)\n",
      "   ---------------------------------------- 331.7/331.7 MB 1.8 MB/s  0:02:56\n",
      "Downloading grpcio-1.80.0-cp39-cp39-win_amd64.whl (4.9 MB)\n",
      "   ---------------------------------------- 4.9/4.9 MB 803.0 kB/s  0:00:06\n",
      "Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)\n",
      "   ---------------------------------------- 5.5/5.5 MB 1.2 MB/s  0:00:04\n",
      "Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)\n",
      "Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)\n",
      "Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
      "Using cached flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)\n",
      "Using cached gast-0.7.0-py3-none-any.whl (22 kB)\n",
      "Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
      "Downloading h5py-3.14.0-cp39-cp39-win_amd64.whl (2.9 MB)\n",
      "   ---------------------------------------- 2.9/2.9 MB 1.5 MB/s  0:00:01\n",
      "Downloading keras-3.10.0-py3-none-any.whl (1.4 MB)\n",
      "   ---------------------------------------- 1.4/1.4 MB 1.2 MB/s  0:00:01\n",
      "Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)\n",
      "Downloading protobuf-6.33.6-cp39-cp39-win_amd64.whl (437 kB)\n",
      "Downloading termcolor-3.1.0-py3-none-any.whl (7.7 kB)\n",
      "Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)\n",
      "Downloading optree-0.19.0-cp39-cp39-win_amd64.whl (327 kB)\n",
      "Downloading rich-15.0.0-py3-none-any.whl (310 kB)\n",
      "Downloading pygments-2.20.0-py3-none-any.whl (1.2 MB)\n",
      "   ---------------------------------------- 1.2/1.2 MB 954.7 kB/s  0:00:01\n",
      "Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)\n",
      "Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)\n",
      "Installing collected packages: namex, libclang, flatbuffers, termcolor, tensorboard-data-server, pygments, protobuf, optree, mdurl, h5py, grpcio, google_pasta, gast, astunparse, absl-py, tensorboard, markdown-it-py, rich, keras, tensorflow\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution - (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -illow (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -tplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -illow (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -tplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -illow (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -tplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\\\Users\\\\FERNANDO\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\clang\\\\native\\\\libclang.dll'\n",
      "Check the permissions.\n",
      "\n",
      "\n",
      "[notice] A new release of pip is available: 25.3 -> 26.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting tensorflow\n",
      "  Using cached tensorflow-2.20.0-cp39-cp39-win_amd64.whl.metadata (4.6 kB)\n",
      "Collecting absl-py>=1.0.0 (from tensorflow)\n",
      "  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)\n",
      "Collecting astunparse>=1.6.0 (from tensorflow)\n",
      "  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)\n",
      "Collecting flatbuffers>=24.3.25 (from tensorflow)\n",
      "  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)\n",
      "Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)\n",
      "  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)\n",
      "Collecting google_pasta>=0.1.1 (from tensorflow)\n",
      "  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)\n",
      "Collecting libclang>=13.0.0 (from tensorflow)\n",
      "  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)\n",
      "Requirement already satisfied: opt_einsum>=2.3.2 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (3.4.0)\n",
      "Requirement already satisfied: packaging in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (25.0)\n",
      "Collecting protobuf>=5.28.0 (from tensorflow)\n",
      "  Using cached protobuf-6.33.6-cp39-cp39-win_amd64.whl.metadata (593 bytes)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorflow) (2.28.1)\n",
      "Requirement already satisfied: setuptools in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorflow) (63.4.1)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (1.17.0)\n",
      "Collecting termcolor>=1.1.0 (from tensorflow)\n",
      "  Using cached termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)\n",
      "Requirement already satisfied: typing_extensions>=3.6.6 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (4.12.2)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorflow) (1.14.1)\n",
      "Collecting grpcio<2.0,>=1.24.3 (from tensorflow)\n",
      "  Using cached grpcio-1.80.0-cp39-cp39-win_amd64.whl.metadata (3.9 kB)\n",
      "Collecting tensorboard~=2.20.0 (from tensorflow)\n",
      "  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)\n",
      "Collecting keras>=3.10.0 (from tensorflow)\n",
      "  Using cached keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (1.26.4)\n",
      "Collecting h5py>=3.11.0 (from tensorflow)\n",
      "  Using cached h5py-3.14.0-cp39-cp39-win_amd64.whl.metadata (2.7 kB)\n",
      "Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorflow) (0.5.4)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (1.26.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorflow) (2022.9.14)\n",
      "Requirement already satisfied: markdown>=2.6.8 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorboard~=2.20.0->tensorflow) (3.3.4)\n",
      "Requirement already satisfied: pillow in c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)\n",
      "Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.20.0->tensorflow)\n",
      "  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from tensorboard~=2.20.0->tensorflow) (2.0.3)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from astunparse>=1.6.0->tensorflow) (0.37.1)\n",
      "Collecting rich (from keras>=3.10.0->tensorflow)\n",
      "  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)\n",
      "Collecting namex (from keras>=3.10.0->tensorflow)\n",
      "  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)\n",
      "Collecting optree (from keras>=3.10.0->tensorflow)\n",
      "  Using cached optree-0.19.0-cp39-cp39-win_amd64.whl.metadata (35 kB)\n",
      "Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.10.0->tensorflow)\n",
      "  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)\n",
      "Collecting pygments<3.0.0,>=2.13.0 (from rich->keras>=3.10.0->tensorflow)\n",
      "  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)\n",
      "Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow)\n",
      "  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)\n",
      "Using cached tensorflow-2.20.0-cp39-cp39-win_amd64.whl (331.7 MB)\n",
      "Using cached grpcio-1.80.0-cp39-cp39-win_amd64.whl (4.9 MB)\n",
      "Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)\n",
      "Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)\n",
      "Using cached absl_py-2.3.1-py3-none-any.whl (135 kB)\n",
      "Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
      "Using cached flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)\n",
      "Using cached gast-0.7.0-py3-none-any.whl (22 kB)\n",
      "Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
      "Using cached h5py-3.14.0-cp39-cp39-win_amd64.whl (2.9 MB)\n",
      "Using cached keras-3.10.0-py3-none-any.whl (1.4 MB)\n",
      "Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)\n",
      "Using cached protobuf-6.33.6-cp39-cp39-win_amd64.whl (437 kB)\n",
      "Using cached termcolor-3.1.0-py3-none-any.whl (7.7 kB)\n",
      "Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)\n",
      "Downloading optree-0.19.0-cp39-cp39-win_amd64.whl (327 kB)\n",
      "Using cached rich-15.0.0-py3-none-any.whl (310 kB)\n",
      "Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)\n",
      "Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)\n",
      "Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)\n",
      "Installing collected packages: namex, libclang, flatbuffers, termcolor, tensorboard-data-server, pygments, protobuf, optree, mdurl, h5py, grpcio, google_pasta, gast, astunparse, absl-py, tensorboard, markdown-it-py, rich, keras, tensorflow\n",
      "\n",
      "Successfully installed absl-py-2.3.1 astunparse-1.6.3 flatbuffers-25.12.19 gast-0.7.0 google_pasta-0.2.0 grpcio-1.80.0 h5py-3.14.0 keras-3.10.0 libclang-18.1.1 markdown-it-py-3.0.0 mdurl-0.1.2 namex-0.1.0 optree-0.19.0 protobuf-6.33.6 pygments-2.20.0 rich-15.0.0 tensorboard-2.20.0 tensorboard-data-server-0.7.2 tensorflow-2.20.0 termcolor-3.1.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution - (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -illow (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -tplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -illow (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -tplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -illow (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -tplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "  WARNING: The script pygmentize.exe is installed in 'C:\\Users\\FERNANDO\\AppData\\Roaming\\Python\\Python39\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "  WARNING: The script tensorboard.exe is installed in 'C:\\Users\\FERNANDO\\AppData\\Roaming\\Python\\Python39\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "  WARNING: The script markdown-it.exe is installed in 'C:\\Users\\FERNANDO\\AppData\\Roaming\\Python\\Python39\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "  WARNING: The scripts import_pb_to_tensorboard.exe, saved_model_cli.exe, tensorboard.exe, tf_upgrade_v2.exe, tflite_convert.exe and toco.exe are installed in 'C:\\Users\\FERNANDO\\AppData\\Roaming\\Python\\Python39\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -andas (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -atplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -illow (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -tplotlib (c:\\users\\fernando\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "spyder 5.2.2 requires pyqt5<5.13, which is not installed.\n",
      "spyder 5.2.2 requires pyqtwebengine<5.13, which is not installed.\n",
      "spyder 5.2.2 requires ipython<8.0.0,>=7.6.0, but you have ipython 8.18.1 which is incompatible.\n",
      "spyder-kernels 2.2.1 requires ipython<8,>=7.6.0; python_version >= \"3\", but you have ipython 8.18.1 which is incompatible.\n",
      "\n",
      "[notice] A new release of pip is available: 25.3 -> 26.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install tensorflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b742486",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "55dd106e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "DENGUE 5-MODEL ENSEMBLE (LSTM identical to standalone best)\n",
      "============================================================\n",
      "[1/5] Spatial adjacency...\n",
      "  Using shapefile spatial weights\n",
      "[2/5] Panel data...\n",
      "  Train: 23500 samples, 28 features, cap=527\n",
      "[3/5] Model 1: Bayesian GAM (MAP Poisson)...\n",
      "  Converged: True, iters=337\n",
      "[4/5] Training correction models...\n",
      "  Training LSTM models (identical to standalone best)...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  LSTM: 100%|██████████████████████████████████████████████████████████████████████████| 25/25 [08:19<00:00, 19.98s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Correction models ready.\n",
      "[5/5] Rolling origin forecast (each model uses its own recursion)...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  Rolling origin: 100%|██████████████████████████████████████████████████████████████████| 6/6 [01:17<00:00, 12.99s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "PERFORMANCE\n",
      "============================================================\n",
      "Bayesian Poisson GAM (Base): RMSE=13.49 MAE=8.99 R2=0.932\n",
      "  W+1: RMSE=12.34 R2=0.947\n",
      "  W+2: RMSE=12.16 R2=0.946\n",
      "  W+3: RMSE=13.57 R2=0.930\n",
      "  W+4: RMSE=15.61 R2=0.902\n",
      "GAM + Random Forest: RMSE=13.39 MAE=8.66 R2=0.933\n",
      "  W+1: RMSE=12.65 R2=0.944\n",
      "  W+2: RMSE=12.19 R2=0.946\n",
      "  W+3: RMSE=12.93 R2=0.936\n",
      "  W+4: RMSE=15.55 R2=0.903\n",
      "GAM + Gradient Boosting: RMSE=14.76 MAE=9.98 R2=0.919\n",
      "  W+1: RMSE=13.53 R2=0.936\n",
      "  W+2: RMSE=14.05 R2=0.928\n",
      "  W+3: RMSE=14.81 R2=0.917\n",
      "  W+4: RMSE=16.50 R2=0.891\n",
      "GAM + LSTM: RMSE=12.66 MAE=8.45 R2=0.940\n",
      "  W+1: RMSE=12.00 R2=0.950\n",
      "  W+2: RMSE=11.43 R2=0.952\n",
      "  W+3: RMSE=12.44 R2=0.941\n",
      "  W+4: RMSE=14.56 R2=0.915\n",
      "GAM + MLP Neural Network: RMSE=12.96 MAE=8.71 R2=0.937\n",
      "  W+1: RMSE=12.19 R2=0.948\n",
      "  W+2: RMSE=11.74 R2=0.949\n",
      "  W+3: RMSE=12.93 R2=0.936\n",
      "  W+4: RMSE=14.80 R2=0.912\n",
      "\n",
      "Saved: model_outputs.json (5.2 MB)\n",
      "\n",
      "=== DONE ===\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "Sri Lanka Dengue Forecasting - 5 Model Ensemble (LSTM identical to standalone best model)\n",
    "\n",
    "Run: python run_models.py -> generates model_outputs.json\n",
    "\"\"\"\n",
    "\n",
    "import os, sys, json, warnings, random\n",
    "from collections import deque, defaultdict\n",
    "from datetime import datetime\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from tqdm import tqdm\n",
    "from scipy.optimize import minimize\n",
    "from scipy.special import gammaln\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n",
    "from sklearn.neural_network import MLPRegressor\n",
    "from sklearn.metrics import mean_squared_error, mean_absolute_error\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import LSTM, Dense, Dropout\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# ========== SEEDS AND DETERMINISM ==========\n",
    "SEED = 42\n",
    "random.seed(SEED)\n",
    "np.random.seed(SEED)\n",
    "tf.random.set_seed(SEED)\n",
    "os.environ['PYTHONHASHSEED'] = str(SEED)\n",
    "os.environ['TF_DETERMINISTIC_OPS'] = '1'\n",
    "tf.config.experimental.enable_op_determinism()\n",
    "\n",
    "# ========== CONFIG ==========\n",
    "DATA_CSV = \"srilanka_dengue_data.csv\"\n",
    "SHAPEFILE = \"C:/Users/FERNANDO/OneDrive - Colombo International Nautical & Engineering College/Desktop/Lap/MSC/Research/Data Sets/lka_adm_20220816_shp/lka_admbnda_adm2_slsd_20220816.shp\"\n",
    "OUTPUT_JSON = \"model_outputs.json\"\n",
    "\n",
    "# ========== HELPERS ==========\n",
    "def bounded_r2(y_true, y_pred):\n",
    "    y_true, y_pred = np.asarray(y_true, float), np.asarray(y_pred, float)\n",
    "    mask = ~np.isnan(y_true) & ~np.isnan(y_pred)\n",
    "    y_true, y_pred = y_true[mask], y_pred[mask]\n",
    "    if len(y_true) < 2:\n",
    "        return 0.0\n",
    "    ss_res = np.sum((y_true - y_pred)**2)\n",
    "    ss_tot = np.sum((y_true - np.mean(y_true))**2)\n",
    "    if ss_tot < 1e-10:\n",
    "        return 0.0\n",
    "    return max(0.0, min(1.0, 1 - ss_res / ss_tot))\n",
    "\n",
    "def neg_log_post(beta, X, y, prior_scale, log_fact):\n",
    "    eta = X @ beta\n",
    "    mu = np.exp(eta)\n",
    "    ll = np.sum(y * eta - mu) - log_fact\n",
    "    lp = -0.5 * np.sum((beta / prior_scale)**2)\n",
    "    return -(ll + lp)\n",
    "\n",
    "def predict_base(X, beta):\n",
    "    return np.exp(np.column_stack([np.ones(X.shape[0]), X]) @ beta)\n",
    "\n",
    "# ========== 1) LOAD DATA ==========\n",
    "print(\"=\"*60 + \"\\nDENGUE 5-MODEL ENSEMBLE (LSTM identical to standalone best)\\n\" + \"=\"*60)\n",
    "if not os.path.exists(DATA_CSV):\n",
    "    print(f\"[ERROR] {DATA_CSV} not found\"); sys.exit(1)\n",
    "\n",
    "df = pd.read_csv(DATA_CSV, parse_dates=['start.date'])\n",
    "dmap = {'NuwaraEliya': 'Nuwara Eliya', 'Hambanthota': 'Hambantota', 'Kalmune': 'Ampara'}\n",
    "df['district'] = df['district'].map(lambda x: dmap.get(x, x))\n",
    "\n",
    "d2p = {\n",
    "    'Colombo': 'Western', 'Gampaha': 'Western', 'Kalutara': 'Western',\n",
    "    'Kandy': 'Central', 'Matale': 'Central', 'Nuwara Eliya': 'Central',\n",
    "    'Galle': 'Southern', 'Hambantota': 'Southern', 'Matara': 'Southern',\n",
    "    'Jaffna': 'Northern', 'Kilinochchi': 'Northern', 'Mannar': 'Northern',\n",
    "    'Vavuniya': 'Northern', 'Mullaitivu': 'Northern',\n",
    "    'Batticaloa': 'Eastern', 'Ampara': 'Eastern', 'Trincomalee': 'Eastern',\n",
    "    'Kurunegala': 'North Western', 'Puttalam': 'North Western',\n",
    "    'Anuradhapura': 'North Central', 'Polonnaruwa': 'North Central',\n",
    "    'Badulla': 'Uva', 'Monaragala': 'Uva',\n",
    "    'Ratnapura': 'Sabaragamuwa', 'Kegalle': 'Sabaragamuwa'\n",
    "}\n",
    "\n",
    "# ========== 2) SPATIAL WEIGHTS ==========\n",
    "print(\"[1/5] Spatial adjacency...\")\n",
    "district_order = sorted(df['district'].unique())\n",
    "if 'Kalmune' in district_order:\n",
    "    district_order.remove('Kalmune')\n",
    "n = len(district_order)\n",
    "\n",
    "if SHAPEFILE and os.path.exists(SHAPEFILE):\n",
    "    try:\n",
    "        import geopandas as gpd\n",
    "        gdf = gpd.read_file(SHAPEFILE)\n",
    "        gdf = gdf[['ADM2_EN', 'geometry']].rename(columns={'ADM2_EN': 'district_shp'})\n",
    "        gdf['district_shp'] = gdf['district_shp'].str.strip().replace({'NuwaraEliya':'Nuwara Eliya'})\n",
    "        gdf = gdf[gdf['district_shp'].isin(district_order)].reset_index(drop=True)\n",
    "        sindex = gdf.sindex\n",
    "        neigh = {i: set() for i in gdf.index}\n",
    "        for i, geom in gdf.geometry.items():\n",
    "            for j in list(sindex.intersection(geom.bounds)):\n",
    "                if i != j and geom.touches(gdf.geometry.iloc[j]):\n",
    "                    neigh[i].add(j); neigh[j].add(i)\n",
    "        district_order = list(gdf['district_shp'])\n",
    "        A = np.zeros((n, n), float)\n",
    "        for i, js in neigh.items():\n",
    "            for j in js:\n",
    "                A[i, j] = 1.0\n",
    "        rs = A.sum(axis=1)\n",
    "        W = A.copy()\n",
    "        for i in range(n):\n",
    "            if rs[i] > 0:\n",
    "                W[i, :] = A[i, :] / rs[i]\n",
    "        print(\"  Using shapefile spatial weights\")\n",
    "    except Exception as e:\n",
    "        print(f\"  Shapefile failed ({e}), using equal weights\")\n",
    "        W = np.ones((n, n), float) / n\n",
    "else:\n",
    "    W = np.ones((n, n), float) / n\n",
    "\n",
    "d2i = {d: i for i, d in enumerate(district_order)}\n",
    "\n",
    "# ========== 3) PANEL DATA ==========\n",
    "print(\"[2/5] Panel data...\")\n",
    "df['week'] = df['start.date'].dt.isocalendar().week\n",
    "df['year'] = df['start.date'].dt.year\n",
    "start_date = df['start.date'].min()\n",
    "df['week_index'] = ((df['start.date'] - start_date).dt.days // 7).astype(int)\n",
    "\n",
    "pivot = df.pivot_table(index='week_index', columns='district', values='cases', aggfunc='sum').fillna(0)\n",
    "pivot = pivot.reindex(columns=district_order, fill_value=0)\n",
    "\n",
    "pl1 = pivot.shift(1).fillna(0)\n",
    "pl2 = pivot.shift(2).fillna(0)\n",
    "pl3 = pivot.shift(3).fillna(0)\n",
    "pl4 = pivot.shift(4).fillna(0)\n",
    "pl5 = pivot.shift(5).fillna(0)\n",
    "\n",
    "sl1 = pl1.values @ W.T\n",
    "sl2 = pl2.values @ W.T\n",
    "\n",
    "records = []\n",
    "for idx, w in enumerate(pivot.index):\n",
    "    for j, d in enumerate(district_order):\n",
    "        records.append({\n",
    "            'week_index': int(w), 'district': d, 'cases': float(pivot.iloc[idx, j]),\n",
    "            'cases_lag1': float(pl1.iloc[idx, j]), 'cases_lag2': float(pl2.iloc[idx, j]),\n",
    "            'cases_lag3': float(pl3.iloc[idx, j]), 'cases_lag4': float(pl4.iloc[idx, j]),\n",
    "            'cases_lag5': float(pl5.iloc[idx, j]),\n",
    "            'spatial_lag1': float(sl1[idx, j]), 'spatial_lag2': float(sl2[idx, j])\n",
    "        })\n",
    "panel = pd.DataFrame(records)\n",
    "panel['Province'] = panel['district'].map(lambda d: d2p.get(d, 'Unknown'))\n",
    "\n",
    "# Feature engineering (identical to standalone)\n",
    "panel['sin52'] = np.sin(2 * np.pi * (panel['week_index'] % 52) / 52)\n",
    "panel['cos52'] = np.cos(2 * np.pi * (panel['week_index'] % 52) / 52)\n",
    "panel['trend'] = panel['week_index'] / panel['week_index'].max()\n",
    "for i in range(1, 6):\n",
    "    panel[f'log_cases_lag{i}'] = np.log1p(panel[f'cases_lag{i}'])\n",
    "panel['log_spatial_lag1'] = np.log1p(np.maximum(panel['spatial_lag1'], 0))\n",
    "panel['log_spatial_lag2'] = np.log1p(np.maximum(panel['spatial_lag2'], 0))\n",
    "panel['rolling_mean_3'] = (panel['log_cases_lag1'] + panel['log_cases_lag2'] + panel['log_cases_lag3']) / 3\n",
    "panel['lag1_x_lag2'] = panel['log_cases_lag1'] * panel['log_cases_lag2']\n",
    "panel['spatial_x_lag1'] = panel['log_spatial_lag1'] * panel['log_cases_lag1']\n",
    "panel['sin52_x_log_cases_lag1'] = panel['sin52'] * panel['log_cases_lag1']\n",
    "panel['cos52_x_log_cases_lag1'] = panel['cos52'] * panel['log_cases_lag1']\n",
    "panel['sin52_sq'] = panel['sin52']**2\n",
    "panel['cos52_sq'] = panel['cos52']**2\n",
    "panel['log_cases_lag1_sq'] = panel['log_cases_lag1']**2\n",
    "panel['log_spatial_lag1_sq'] = panel['log_spatial_lag1']**2\n",
    "panel = panel.dropna()\n",
    "\n",
    "prov_d = pd.get_dummies(panel['Province'], prefix='prov').astype(int)\n",
    "panel = pd.concat([panel, prov_d], axis=1)\n",
    "\n",
    "# Train/validation split (validation starts 2025-01-01)\n",
    "validation_start = pd.Timestamp(\"2025-01-01\")\n",
    "vsw = int(((validation_start - start_date).days // 7))\n",
    "train_data = panel[panel['week_index'] < vsw].copy()\n",
    "val_data = panel[panel['week_index'] >= vsw].copy()\n",
    "cap_max = max(1.5 * train_data['cases'].quantile(0.99), 100)\n",
    "\n",
    "feature_cols = [\n",
    "    'sin52', 'cos52', 'trend',\n",
    "    'log_cases_lag1', 'log_cases_lag2', 'log_cases_lag3', 'log_cases_lag4', 'log_cases_lag5',\n",
    "    'log_spatial_lag1', 'log_spatial_lag2', 'rolling_mean_3',\n",
    "    'sin52_sq', 'cos52_sq', 'log_cases_lag1_sq', 'log_spatial_lag1_sq',\n",
    "    'lag1_x_lag2', 'spatial_x_lag1',\n",
    "    'sin52_x_log_cases_lag1', 'cos52_x_log_cases_lag1'\n",
    "] + list(prov_d.columns)\n",
    "feature_cols = [c for c in feature_cols if c in panel.columns]\n",
    "\n",
    "Xr = train_data[feature_cols].values.astype(np.float64)\n",
    "y = train_data['cases'].values.astype(np.float64)\n",
    "Xi = np.column_stack([np.ones(len(Xr)), Xr])\n",
    "mask = ~np.isnan(Xr).any(axis=1)\n",
    "Xr, y, Xi = Xr[mask], y[mask], Xi[mask]\n",
    "print(f\"  Train: {len(y)} samples, {len(feature_cols)} features, cap={cap_max:.0f}\")\n",
    "\n",
    "# ========== 4) BASE GAM (MAP Poisson) ==========\n",
    "print(\"[3/5] Model 1: Bayesian GAM (MAP Poisson)...\")\n",
    "log_fact = np.sum(gammaln(y + 1))\n",
    "res = minimize(neg_log_post, np.zeros(Xi.shape[1]), args=(Xi, y, 5.0, log_fact),\n",
    "               method='L-BFGS-B', options={'maxiter': 2000, 'disp': False})\n",
    "beta_map = res.x\n",
    "print(f\"  Converged: {res.success}, iters={res.nit}\")\n",
    "\n",
    "base_pred_train = predict_base(Xr, beta_map)\n",
    "train_clean = train_data.iloc[mask].copy()\n",
    "train_clean['residual'] = y - base_pred_train\n",
    "train_clean = train_clean.sort_values(['district', 'week_index'])\n",
    "\n",
    "# ========== 5) CORRECTION MODELS ==========\n",
    "print(\"[4/5] Training correction models...\")\n",
    "scaler = StandardScaler()\n",
    "Xr_scaled = scaler.fit_transform(Xr)\n",
    "\n",
    "# Random Forest (district-wise)\n",
    "rf_models = {}\n",
    "for d in district_order:\n",
    "    sub = train_clean[train_clean['district'] == d]\n",
    "    if len(sub) >= 10:\n",
    "        rf_models[d] = RandomForestRegressor(n_estimators=100, random_state=SEED, n_jobs=-1)\n",
    "        rf_models[d].fit(sub[feature_cols].values, sub['residual'].values)\n",
    "    else:\n",
    "        rf_models[d] = None\n",
    "\n",
    "# Gradient Boosting (district-wise)\n",
    "gb_models = {}\n",
    "for d in district_order:\n",
    "    sub = train_clean[train_clean['district'] == d]\n",
    "    if len(sub) >= 10:\n",
    "        gb_models[d] = GradientBoostingRegressor(n_estimators=100, max_depth=5, learning_rate=0.1, random_state=SEED)\n",
    "        gb_models[d].fit(sub[feature_cols].values, sub['residual'].values)\n",
    "    else:\n",
    "        gb_models[d] = None\n",
    "\n",
    "# MLP (scaled, district-wise) – unchanged to keep R²≈0.937\n",
    "mlp_models = {}\n",
    "for d in district_order:\n",
    "    sub = train_clean[train_clean['district'] == d]\n",
    "    if len(sub) >= 10:\n",
    "        mlp_models[d] = MLPRegressor(hidden_layer_sizes=(50,25), activation='relu', solver='adam',\n",
    "                                     max_iter=500, random_state=SEED, early_stopping=True)\n",
    "        Xs = scaler.transform(sub[feature_cols].values)\n",
    "        mlp_models[d].fit(Xs, sub['residual'].values)\n",
    "    else:\n",
    "        mlp_models[d] = None\n",
    "\n",
    "# LSTM – EXACT SAME AS STANDALONE BEST MODEL (window=52, 32 units, 30 epochs, batch=32, val_split=0.1)\n",
    "window = 52\n",
    "lstm_models = {}\n",
    "print(\"  Training LSTM models (identical to standalone best)...\")\n",
    "for d in tqdm(district_order, desc=\"  LSTM\"):\n",
    "    resid_series = train_clean[train_clean['district'] == d]['residual'].values\n",
    "    if len(resid_series) <= window:\n",
    "        lstm_models[d] = None\n",
    "        continue\n",
    "    Xs, ys = [], []\n",
    "    for i in range(len(resid_series) - window):\n",
    "        Xs.append(resid_series[i:i+window].reshape(-1, 1))\n",
    "        ys.append(resid_series[i+window])\n",
    "    Xs = np.array(Xs, dtype=np.float32)\n",
    "    ys = np.array(ys, dtype=np.float32)\n",
    "    model = Sequential([\n",
    "        LSTM(32, dropout=0.2, recurrent_dropout=0.2, input_shape=(window, 1)),\n",
    "        Dense(16, activation='relu'),\n",
    "        Dense(1)\n",
    "    ])\n",
    "    model.compile(optimizer=Adam(0.001), loss='mse')\n",
    "    model.fit(Xs, ys, epochs=30, batch_size=32, validation_split=0.1, verbose=0)   # <-- same as standalone\n",
    "    lstm_models[d] = model\n",
    "print(\"  Correction models ready.\")\n",
    "\n",
    "# ========== 6) ROLLING ORIGIN FORECAST ==========\n",
    "print(\"[5/5] Rolling origin forecast (each model uses its own recursion)...\")\n",
    "vw = sorted(val_data['week_index'].unique())\n",
    "mw = max(vw)\n",
    "actual = {(r['week_index'], r['district']): r['cases'] for _, r in panel.iterrows()}\n",
    "panel['base_pred'] = predict_base(panel[feature_cols].values.astype(np.float64), beta_map)\n",
    "panel['residual'] = panel['cases'] - panel['base_pred']\n",
    "\n",
    "results = {key: [] for key in ['model1_base', 'model2_rf', 'model3_gb', 'model4_lstm', 'model5_mlp']}\n",
    "\n",
    "for origin_week in tqdm(vw[:-4], desc=\"  Rolling origin\"):\n",
    "    # Initialise separate case histories for each model\n",
    "    case_hist_base = {}\n",
    "    case_hist_rf = {}\n",
    "    case_hist_gb = {}\n",
    "    case_hist_mlp = {}\n",
    "    case_hist_lstm = {}\n",
    "    resid_hist = {}\n",
    "    for d in district_order:\n",
    "        base_hist = [actual.get((origin_week - i, d), 0) for i in range(5, -1, -1)]\n",
    "        case_hist_base[d] = deque(base_hist, maxlen=6)\n",
    "        case_hist_rf[d] = deque(base_hist, maxlen=6)\n",
    "        case_hist_gb[d] = deque(base_hist, maxlen=6)\n",
    "        case_hist_mlp[d] = deque(base_hist, maxlen=6)\n",
    "        case_hist_lstm[d] = deque(base_hist, maxlen=6)\n",
    "        hist_res = []\n",
    "        for w in range(origin_week - window + 1, origin_week + 1):\n",
    "            if w < 0:\n",
    "                hist_res.append(0.0)\n",
    "            else:\n",
    "                val = panel[(panel['week_index'] == w) & (panel['district'] == d)]['residual'].values\n",
    "                hist_res.append(val[0] if len(val) > 0 else 0.0)\n",
    "        resid_hist[d] = deque(hist_res, maxlen=window)\n",
    "\n",
    "    cur_vec_base = np.array([actual.get((origin_week, d), 0) for d in district_order])\n",
    "    cur_vec_rf = cur_vec_base.copy()\n",
    "    cur_vec_gb = cur_vec_base.copy()\n",
    "    cur_vec_mlp = cur_vec_base.copy()\n",
    "    cur_vec_lstm = cur_vec_base.copy()\n",
    "\n",
    "    for ahead in [1, 2, 3, 4]:\n",
    "        fw = origin_week + ahead\n",
    "        if fw > mw:\n",
    "            continue\n",
    "        base = val_data[val_data['week_index'] == fw].copy()\n",
    "        if base.empty:\n",
    "            continue\n",
    "\n",
    "        # ----- Base/RF/GB/MLP group (use base predictions for recursion) -----\n",
    "        l1 = cur_vec_base.copy()\n",
    "        l2 = np.array([case_hist_base[d][-2] for d in district_order])\n",
    "        l3 = np.array([case_hist_base[d][-3] for d in district_order])\n",
    "        l4 = np.array([case_hist_base[d][-4] for d in district_order])\n",
    "        l5 = np.array([case_hist_base[d][-5] for d in district_order])\n",
    "        s1 = l1 @ W.T\n",
    "        s2 = l2 @ W.T\n",
    "\n",
    "        rows = []\n",
    "        for d in base['district']:\n",
    "            idx = d2i.get(d)\n",
    "            if idx is None:\n",
    "                v1=v2=v3=v4=v5=s1v=s2v=0\n",
    "            else:\n",
    "                v1, v2, v3, v4, v5 = l1[idx], l2[idx], l3[idx], l4[idx], l5[idx]\n",
    "                s1v, s2v = s1[idx], s2[idx]\n",
    "            log1 = np.log1p(max(v1,0)); log2 = np.log1p(max(v2,0)); log3 = np.log1p(max(v3,0))\n",
    "            log4 = np.log1p(max(v4,0)); log5 = np.log1p(max(v5,0))\n",
    "            ls1 = np.log1p(max(s1v,0)); ls2 = np.log1p(max(s2v,0))\n",
    "            s52 = np.sin(2*np.pi*(fw%52)/52); c52 = np.cos(2*np.pi*(fw%52)/52)\n",
    "            row = {\n",
    "                'sin52': s52, 'cos52': c52, 'trend': fw / panel['week_index'].max(),\n",
    "                'log_cases_lag1': log1, 'log_cases_lag2': log2, 'log_cases_lag3': log3,\n",
    "                'log_cases_lag4': log4, 'log_cases_lag5': log5,\n",
    "                'log_spatial_lag1': ls1, 'log_spatial_lag2': ls2,\n",
    "                'rolling_mean_3': (log1+log2+log3)/3,\n",
    "                'lag1_x_lag2': log1*log2, 'spatial_x_lag1': ls1*log1,\n",
    "                'sin52_sq': s52**2, 'cos52_sq': c52**2,\n",
    "                'log_cases_lag1_sq': log1**2, 'log_spatial_lag1_sq': ls1**2,\n",
    "                'sin52_x_log_cases_lag1': s52*log1,\n",
    "                'cos52_x_log_cases_lag1': c52*log1,\n",
    "            }\n",
    "            for pcol in prov_d.columns:\n",
    "                row[pcol] = 1 if pcol.replace('prov_','') == d2p.get(d,'') else 0\n",
    "            rows.append(row)\n",
    "        fdf = pd.DataFrame(rows)\n",
    "        for c in feature_cols:\n",
    "            if c not in fdf.columns:\n",
    "                fdf[c] = 0\n",
    "        Xf = fdf[feature_cols].values.astype(np.float64)\n",
    "        base_pred = predict_base(Xf, beta_map)\n",
    "        base_pred = np.clip(base_pred, 0, cap_max)\n",
    "\n",
    "        # RF correction\n",
    "        rf_pred = base_pred.copy()\n",
    "        for i, d in enumerate(base['district']):\n",
    "            if rf_models.get(d):\n",
    "                rf_pred[i] += rf_models[d].predict(Xf[i].reshape(1, -1))[0]\n",
    "        rf_pred = np.clip(rf_pred, 0, cap_max)\n",
    "\n",
    "        # GB correction\n",
    "        gb_pred = base_pred.copy()\n",
    "        for i, d in enumerate(base['district']):\n",
    "            if gb_models.get(d):\n",
    "                gb_pred[i] += gb_models[d].predict(Xf[i].reshape(1, -1))[0]\n",
    "        gb_pred = np.clip(gb_pred, 0, cap_max)\n",
    "\n",
    "        # MLP correction (scaled)\n",
    "        mlp_pred = base_pred.copy()\n",
    "        Xf_scaled = scaler.transform(Xf)\n",
    "        for i, d in enumerate(base['district']):\n",
    "            if mlp_models.get(d):\n",
    "                mlp_pred[i] += mlp_models[d].predict(Xf_scaled[i].reshape(1, -1))[0]\n",
    "        mlp_pred = np.clip(mlp_pred, 0, cap_max)\n",
    "\n",
    "        # ----- LSTM group (independent recursion using its own corrected forecasts) -----\n",
    "        l1_lstm = cur_vec_lstm.copy()\n",
    "        l2_lstm = np.array([case_hist_lstm[d][-2] for d in district_order])\n",
    "        l3_lstm = np.array([case_hist_lstm[d][-3] for d in district_order])\n",
    "        l4_lstm = np.array([case_hist_lstm[d][-4] for d in district_order])\n",
    "        l5_lstm = np.array([case_hist_lstm[d][-5] for d in district_order])\n",
    "        s1_lstm = l1_lstm @ W.T\n",
    "        s2_lstm = l2_lstm @ W.T\n",
    "\n",
    "        rows_lstm = []\n",
    "        for d in base['district']:\n",
    "            idx = d2i.get(d)\n",
    "            if idx is None:\n",
    "                v1=v2=v3=v4=v5=s1v=s2v=0\n",
    "            else:\n",
    "                v1, v2, v3, v4, v5 = l1_lstm[idx], l2_lstm[idx], l3_lstm[idx], l4_lstm[idx], l5_lstm[idx]\n",
    "                s1v, s2v = s1_lstm[idx], s2_lstm[idx]\n",
    "            log1 = np.log1p(max(v1,0)); log2 = np.log1p(max(v2,0)); log3 = np.log1p(max(v3,0))\n",
    "            log4 = np.log1p(max(v4,0)); log5 = np.log1p(max(v5,0))\n",
    "            ls1 = np.log1p(max(s1v,0)); ls2 = np.log1p(max(s2v,0))\n",
    "            s52 = np.sin(2*np.pi*(fw%52)/52); c52 = np.cos(2*np.pi*(fw%52)/52)\n",
    "            row = {\n",
    "                'sin52': s52, 'cos52': c52, 'trend': fw / panel['week_index'].max(),\n",
    "                'log_cases_lag1': log1, 'log_cases_lag2': log2, 'log_cases_lag3': log3,\n",
    "                'log_cases_lag4': log4, 'log_cases_lag5': log5,\n",
    "                'log_spatial_lag1': ls1, 'log_spatial_lag2': ls2,\n",
    "                'rolling_mean_3': (log1+log2+log3)/3,\n",
    "                'lag1_x_lag2': log1*log2, 'spatial_x_lag1': ls1*log1,\n",
    "                'sin52_sq': s52**2, 'cos52_sq': c52**2,\n",
    "                'log_cases_lag1_sq': log1**2, 'log_spatial_lag1_sq': ls1**2,\n",
    "                'sin52_x_log_cases_lag1': s52*log1,\n",
    "                'cos52_x_log_cases_lag1': c52*log1,\n",
    "            }\n",
    "            for pcol in prov_d.columns:\n",
    "                row[pcol] = 1 if pcol.replace('prov_','') == d2p.get(d,'') else 0\n",
    "            rows_lstm.append(row)\n",
    "        fdf_lstm = pd.DataFrame(rows_lstm)\n",
    "        for c in feature_cols:\n",
    "            if c not in fdf_lstm.columns:\n",
    "                fdf_lstm[c] = 0\n",
    "        Xf_lstm = fdf_lstm[feature_cols].values.astype(np.float64)\n",
    "        base_pred_lstm = predict_base(Xf_lstm, beta_map)\n",
    "        base_pred_lstm = np.clip(base_pred_lstm, 0, cap_max)\n",
    "\n",
    "        lstm_pred = base_pred_lstm.copy()\n",
    "        for i, d in enumerate(base['district']):\n",
    "            if lstm_models.get(d):\n",
    "                hist = list(resid_hist[d])\n",
    "                if len(hist) != window:\n",
    "                    hist = [0.0] * (window - len(hist)) + hist\n",
    "                seq = np.array(hist).reshape(1, window, 1)\n",
    "                resid_corr = lstm_models[d].predict(seq, verbose=0)[0,0]\n",
    "                lstm_pred[i] += resid_corr\n",
    "        lstm_pred = np.clip(lstm_pred, 0, cap_max)\n",
    "\n",
    "        # Store forecasts\n",
    "        for j, (_, row) in enumerate(base.iterrows()):\n",
    "            results['model1_base'].append({\n",
    "                'origin_week': origin_week, 'forecast_week': fw, 'weeks_ahead': ahead,\n",
    "                'district': row['district'], 'actual_cases': row['cases'], 'predicted_cases': base_pred[j]\n",
    "            })\n",
    "            results['model2_rf'].append({\n",
    "                'origin_week': origin_week, 'forecast_week': fw, 'weeks_ahead': ahead,\n",
    "                'district': row['district'], 'actual_cases': row['cases'], 'predicted_cases': rf_pred[j]\n",
    "            })\n",
    "            results['model3_gb'].append({\n",
    "                'origin_week': origin_week, 'forecast_week': fw, 'weeks_ahead': ahead,\n",
    "                'district': row['district'], 'actual_cases': row['cases'], 'predicted_cases': gb_pred[j]\n",
    "            })\n",
    "            results['model4_lstm'].append({\n",
    "                'origin_week': origin_week, 'forecast_week': fw, 'weeks_ahead': ahead,\n",
    "                'district': row['district'], 'actual_cases': row['cases'], 'predicted_cases': lstm_pred[j]\n",
    "            })\n",
    "            results['model5_mlp'].append({\n",
    "                'origin_week': origin_week, 'forecast_week': fw, 'weeks_ahead': ahead,\n",
    "                'district': row['district'], 'actual_cases': row['cases'], 'predicted_cases': mlp_pred[j]\n",
    "            })\n",
    "\n",
    "        # Update recursions\n",
    "        # Base/RF/GB/MLP: use base_pred (uncorrected)\n",
    "        new_vec_base = np.zeros(n)\n",
    "        for i, d in enumerate(base['district']):\n",
    "            idx = d2i.get(d)\n",
    "            if idx is not None:\n",
    "                new_vec_base[idx] = base_pred[i]\n",
    "                case_hist_base[d].append(base_pred[i])\n",
    "                case_hist_rf[d].append(base_pred[i])\n",
    "                case_hist_gb[d].append(base_pred[i])\n",
    "                case_hist_mlp[d].append(base_pred[i])\n",
    "        cur_vec_base = new_vec_base\n",
    "        cur_vec_rf = new_vec_base\n",
    "        cur_vec_gb = new_vec_base\n",
    "        cur_vec_mlp = new_vec_base\n",
    "\n",
    "        # LSTM: use lstm_pred (corrected)\n",
    "        new_vec_lstm = np.zeros(n)\n",
    "        for i, d in enumerate(base['district']):\n",
    "            idx = d2i.get(d)\n",
    "            if idx is not None:\n",
    "                new_vec_lstm[idx] = lstm_pred[i]\n",
    "                case_hist_lstm[d].append(lstm_pred[i])\n",
    "        cur_vec_lstm = new_vec_lstm\n",
    "\n",
    "        # Residual history update (same as standalone)\n",
    "        for i, d in enumerate(base['district']):\n",
    "            resid_hist[d].append(lstm_pred[i] - base_pred_lstm[i])\n",
    "\n",
    "# ========== 7) METRICS ==========\n",
    "print(\"\\n\" + \"=\"*60 + \"\\nPERFORMANCE\\n\" + \"=\"*60)\n",
    "model_info = {\n",
    "    'model1_base': {'name': 'Bayesian Poisson GAM (Base)', 'short': 'Base GAM'},\n",
    "    'model2_rf': {'name': 'GAM + Random Forest', 'short': 'GAM+RF'},\n",
    "    'model3_gb': {'name': 'GAM + Gradient Boosting', 'short': 'GAM+GB'},\n",
    "    'model4_lstm': {'name': 'GAM + LSTM', 'short': 'GAM+LSTM'},\n",
    "    'model5_mlp': {'name': 'GAM + MLP Neural Network', 'short': 'GAM+MLP'}\n",
    "}\n",
    "final_output = {}\n",
    "for key, info in model_info.items():\n",
    "    df_pred = pd.DataFrame(results[key]).dropna()\n",
    "    if len(df_pred) == 0:\n",
    "        continue\n",
    "    yt, yp = df_pred['actual_cases'].values, df_pred['predicted_cases'].values\n",
    "    rmse = float(np.sqrt(mean_squared_error(yt, yp)))\n",
    "    mae = float(mean_absolute_error(yt, yp))\n",
    "    r2 = float(bounded_r2(yt, yp))\n",
    "    horizon = {}\n",
    "    for w in sorted(df_pred['weeks_ahead'].unique()):\n",
    "        sub = df_pred[df_pred['weeks_ahead'] == w]\n",
    "        h_rmse = float(np.sqrt(mean_squared_error(sub['actual_cases'], sub['predicted_cases'])))\n",
    "        h_mae = float(mean_absolute_error(sub['actual_cases'], sub['predicted_cases']))\n",
    "        h_r2 = float(bounded_r2(sub['actual_cases'], sub['predicted_cases']))\n",
    "        horizon[int(w)] = {'rmse': h_rmse, 'mae': h_mae, 'r2': h_r2}\n",
    "    district_fc = defaultdict(list)\n",
    "    for _, row in df_pred.iterrows():\n",
    "        district_fc[row['district']].append({\n",
    "            'week': int(row['forecast_week']), 'actual': float(row['actual_cases']),\n",
    "            'predicted': float(row['predicted_cases']), 'weeks_ahead': int(row['weeks_ahead'])\n",
    "        })\n",
    "    final_output[key] = {\n",
    "        'name': info['name'], 'short_name': info['short'],\n",
    "        'overall': {'rmse': rmse, 'mae': mae, 'r2': r2},\n",
    "        'by_horizon': horizon,\n",
    "        'forecasts': dict(district_fc),\n",
    "        'raw': df_pred.to_dict('records')\n",
    "    }\n",
    "    print(f\"{info['name']}: RMSE={rmse:.2f} MAE={mae:.2f} R2={r2:.3f}\")\n",
    "    for w, m in sorted(horizon.items()):\n",
    "        print(f\"  W+{w}: RMSE={m['rmse']:.2f} R2={m['r2']:.3f}\")\n",
    "\n",
    "# Historical data\n",
    "historical = defaultdict(list)\n",
    "for _, row in panel.iterrows():\n",
    "    historical[row['district']].append({\n",
    "        'year': int(row['week_index'] // 52 + 2006),\n",
    "        'week': int(row['week_index'] % 52 + 1),\n",
    "        'cases': float(row['cases'])\n",
    "    })\n",
    "\n",
    "output = {\n",
    "    'meta': {\n",
    "        'generated_at': datetime.now().isoformat(),\n",
    "        'models': list(model_info.keys()),\n",
    "        'model_names': {k: v['name'] for k, v in model_info.items()},\n",
    "        'validation_start': '2025-01-01',\n",
    "        'n_districts': len(district_order),\n",
    "        'districts': district_order,\n",
    "        'version': '5-model_ensemble_lstm_standalone_identical'\n",
    "    },\n",
    "    'historical': dict(historical),\n",
    "    'model_outputs': final_output,\n",
    "    'districts': {\n",
    "        d: {'coordinates': {'lat': 7.8731, 'lng': 80.7718},\n",
    "            'historical': historical[d], 'province': d2p.get(d, 'Unknown')}\n",
    "        for d in district_order\n",
    "    }\n",
    "}\n",
    "with open(OUTPUT_JSON, 'w') as f:\n",
    "    json.dump(output, f, indent=2, default=str)\n",
    "print(f\"\\nSaved: {OUTPUT_JSON} ({(os.path.getsize(OUTPUT_JSON) / 1024 / 1024):.1f} MB)\")\n",
    "print(\"\\n=== DONE ===\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1531ad2a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "352f7009",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
